# Generated by Django 3.0.7 on 2020-06-26 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200626_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followrs',
            field=models.ManyToManyField(blank=True, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
