# Generated by Django 3.0.7 on 2020-06-26 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200626_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followrs',
            new_name='followers',
        ),
    ]
